---
version: 2
jobs:
    configure_env_vars:
        <<: *defaults

        docker:
            - image: quay.io/pantheon-public/build-tools-ci:5.x

        steps:
            - checkout


jobs:
  test:
    docker:
      - image: quay.io/pantheon-public/build-tools-ci:6.x

    working_directory: ~/upstream-prototypes

    steps:
      - ./tests/test-upstream-install.sh 1-wikimedia-merge
      - ./tests/test-upstream-install.sh 2-path-repository
      - ./tests/test-upstream-install.sh 3-external-project

workflows:
  version: 2
  run-tests:
    jobs:
      - test
