---
version: 2

jobs:
  test:
    docker:
      - image: quay.io/pantheon-public/build-tools-ci:6.x

    working_directory: ~/upstream-prototypes

    steps:
      - checkout
      - run: ./tests/test-upstream-install.sh 1-wikimedia-merge
      - run: ./tests/test-upstream-install.sh 2-path-repository
      - run: ./tests/test-upstream-install.sh 3-external-project

workflows:
  version: 2
  run-tests:
    jobs:
      - test
